### PR TITLE
refactor: update shared preferences usage

### PR DESCRIPTION
**Pull request by juaoose**
not conviced it is cleaner because of navigation :\

### CODE REVIEW

**Comment by kevmo314** [comment]
> not conviced it is cleaner because of navigation :\

You mean having to pass `prefs` everywhere?

**Comment by juaoose** [comment]
> > not conviced it is cleaner because of navigation :\
> 
> You mean having to pass `prefs` everywhere?

Yeah, I guess it happens because of not using named routes

**Comment by kevmo314** [comment]
I see. One idea might be to fetch `SharedPreferences` in the component itself, that way it doesn't have to be passed around. Alternatively, it could be injected, I think it's more ok to inject `SharedPreferences` than the model.

I think the main value in this approach is not having a separate model that basically wraps `SharedPreferences`. I agree though that passing it around is a little annoying.

**Comment by juaoose** [comment]
> I see. One idea might be to fetch `SharedPreferences` in the component itself, that way it doesn't have to be passed around. Alternatively, it could be injected, I think it's more ok to inject `SharedPreferences` than the model.
> 
> I think the main value in this approach is not having a separate model that basically wraps `SharedPreferences`. I agree though that passing it around is a little annoying.

Is this good for now? I thought I would get to the alternatives but haven't been able to.

**Pull request closed without merging**
